// <auto-generated />
using System;
using LabourReporting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LabourReporting.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200302171656_addedNulltoOperator")]
    partial class addedNulltoOperator
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LabourReporting.Models.LabourReport", b =>
                {
                    b.Property<int>("LabourReportId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("AllowedTime");

                    b.Property<string>("Comments");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ItemNo")
                        .IsRequired();

                    b.Property<int>("OperatorID");

                    b.Property<double>("Quantity");

                    b.Property<double?>("Scrap");

                    b.Property<int>("ShopOrder");

                    b.Property<string>("SupervisorComments");

                    b.Property<float>("TotalTime");

                    b.HasKey("LabourReportId");

                    b.HasIndex("OperatorID");

                    b.ToTable("LabourReports");
                });

            modelBuilder.Entity("LabourReporting.Models.NcrTag", b =>
                {
                    b.Property<double>("Tag_No");

                    b.Property<string>("Colour");

                    b.Property<DateTime>("Date_Rej");

                    b.Property<string>("Defect");

                    b.Property<string>("Disposition")
                        .IsRequired();

                    b.Property<string>("Item")
                        .IsRequired();

                    b.Property<string>("NcrComments");

                    b.Property<int?>("OperationNumber");

                    b.Property<int?>("OperatorId");

                    b.Property<int?>("Order_number");

                    b.Property<int?>("Put_Up");

                    b.Property<double>("Qty");

                    b.Property<string>("SupervisorSignature");

                    b.Property<int?>("WorkStationId");

                    b.HasKey("Tag_No");

                    b.HasIndex("OperatorId");

                    b.HasIndex("WorkStationId");

                    b.ToTable("NcrTags");
                });

            modelBuilder.Entity("LabourReporting.Models.Operator", b =>
                {
                    b.Property<int>("OperatorID");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("OperatorID");

                    b.ToTable("Operators");

                    b.HasData(
                        new
                        {
                            OperatorID = 3494,
                            FirstName = "Adam",
                            LastName = "Macdonald"
                        },
                        new
                        {
                            OperatorID = 2873,
                            FirstName = "Albert",
                            LastName = "Postma"
                        },
                        new
                        {
                            OperatorID = 3460,
                            FirstName = "Alex",
                            LastName = "Begg"
                        },
                        new
                        {
                            OperatorID = 3679,
                            FirstName = "Alexander",
                            LastName = "Thomas"
                        },
                        new
                        {
                            OperatorID = 3449,
                            FirstName = "Ali",
                            LastName = "Sharifi"
                        },
                        new
                        {
                            OperatorID = 3510,
                            FirstName = "Andrew",
                            LastName = "Scott"
                        },
                        new
                        {
                            OperatorID = 3485,
                            FirstName = "Angela",
                            LastName = "Boudreau"
                        },
                        new
                        {
                            OperatorID = 3417,
                            FirstName = "Angus",
                            LastName = "Young"
                        },
                        new
                        {
                            OperatorID = 3058,
                            FirstName = "Ashley",
                            LastName = "Mcbride"
                        },
                        new
                        {
                            OperatorID = 2834,
                            FirstName = "Barry",
                            LastName = "Alexander"
                        },
                        new
                        {
                            OperatorID = 3049,
                            FirstName = "Benson",
                            LastName = "Downes"
                        },
                        new
                        {
                            OperatorID = 2745,
                            FirstName = "Bill",
                            LastName = "Scott"
                        },
                        new
                        {
                            OperatorID = 3604,
                            FirstName = "Brandon",
                            LastName = "Abbott"
                        },
                        new
                        {
                            OperatorID = 3654,
                            FirstName = "Brent",
                            LastName = "Hargreaves"
                        },
                        new
                        {
                            OperatorID = 3154,
                            FirstName = "Brian",
                            LastName = "Baggaley"
                        },
                        new
                        {
                            OperatorID = 3183,
                            FirstName = "Brian",
                            LastName = "Davey"
                        },
                        new
                        {
                            OperatorID = 3559,
                            FirstName = "Bryan",
                            LastName = "Thorpe"
                        },
                        new
                        {
                            OperatorID = 3672,
                            FirstName = "Carlos",
                            LastName = "HerreraHimeliz"
                        },
                        new
                        {
                            OperatorID = 3571,
                            FirstName = "Carmel",
                            LastName = "Scott"
                        },
                        new
                        {
                            OperatorID = 3572,
                            FirstName = "Chris",
                            LastName = "Gilmour"
                        },
                        new
                        {
                            OperatorID = 3053,
                            FirstName = "Chris",
                            LastName = "Hall"
                        },
                        new
                        {
                            OperatorID = 3496,
                            FirstName = "Chris",
                            LastName = "Lee"
                        },
                        new
                        {
                            OperatorID = 3495,
                            FirstName = "Chris",
                            LastName = "Pot"
                        },
                        new
                        {
                            OperatorID = 3626,
                            FirstName = "Christopher",
                            LastName = "Jones"
                        },
                        new
                        {
                            OperatorID = 2700,
                            FirstName = "Claude",
                            LastName = "Alunni"
                        },
                        new
                        {
                            OperatorID = 3428,
                            FirstName = "Colleen",
                            LastName = "Walsh"
                        },
                        new
                        {
                            OperatorID = 3543,
                            FirstName = "Connor",
                            LastName = "Turland"
                        },
                        new
                        {
                            OperatorID = 3119,
                            FirstName = "Cory",
                            LastName = "Warner"
                        },
                        new
                        {
                            OperatorID = 3605,
                            FirstName = "Courtney",
                            LastName = "Sutton"
                        },
                        new
                        {
                            OperatorID = 3611,
                            FirstName = "Dale",
                            LastName = "Spencer"
                        },
                        new
                        {
                            OperatorID = 3655,
                            FirstName = "Daniel",
                            LastName = "Beasley"
                        },
                        new
                        {
                            OperatorID = 3503,
                            FirstName = "Daniel",
                            LastName = "Sonier"
                        },
                        new
                        {
                            OperatorID = 3542,
                            FirstName = "David",
                            LastName = "Kort"
                        },
                        new
                        {
                            OperatorID = 2849,
                            FirstName = "David",
                            LastName = "Mitchell"
                        },
                        new
                        {
                            OperatorID = 2980,
                            FirstName = "David",
                            LastName = "Steves"
                        },
                        new
                        {
                            OperatorID = 3091,
                            FirstName = "Dayrell",
                            LastName = "Bate"
                        },
                        new
                        {
                            OperatorID = 3171,
                            FirstName = "Deanne",
                            LastName = "Dobney"
                        },
                        new
                        {
                            OperatorID = 3013,
                            FirstName = "Don",
                            LastName = "Chartier"
                        },
                        new
                        {
                            OperatorID = 3175,
                            FirstName = "Donald",
                            LastName = "Davis"
                        },
                        new
                        {
                            OperatorID = 2914,
                            FirstName = "Doug",
                            LastName = "Beattie"
                        },
                        new
                        {
                            OperatorID = 3343,
                            FirstName = "Douglas",
                            LastName = "Zehr"
                        },
                        new
                        {
                            OperatorID = 3687,
                            FirstName = "Dustin",
                            LastName = "Stillman"
                        },
                        new
                        {
                            OperatorID = 3059,
                            FirstName = "Dwayne",
                            LastName = "Schwantz"
                        },
                        new
                        {
                            OperatorID = 3108,
                            FirstName = "Edward",
                            LastName = "O'Brien"
                        },
                        new
                        {
                            OperatorID = 3649,
                            FirstName = "Eric",
                            LastName = "Barnes"
                        },
                        new
                        {
                            OperatorID = 3065,
                            FirstName = "Erik",
                            LastName = "Jensen"
                        },
                        new
                        {
                            OperatorID = 3291,
                            FirstName = "Ernest",
                            LastName = "Delong"
                        },
                        new
                        {
                            OperatorID = 3161,
                            FirstName = "Fabian",
                            LastName = "Austin"
                        },
                        new
                        {
                            OperatorID = 3617,
                            FirstName = "Finn",
                            LastName = "Jorgensen"
                        },
                        new
                        {
                            OperatorID = 2593,
                            FirstName = "Gary",
                            LastName = "Long"
                        },
                        new
                        {
                            OperatorID = 3120,
                            FirstName = "Glenn",
                            LastName = "Bluemel"
                        },
                        new
                        {
                            OperatorID = 3522,
                            FirstName = "Gordon",
                            LastName = "Battersby"
                        },
                        new
                        {
                            OperatorID = 2982,
                            FirstName = "Gregory",
                            LastName = "Bresett"
                        },
                        new
                        {
                            OperatorID = 2756,
                            FirstName = "Gregory",
                            LastName = "Vandenberg"
                        },
                        new
                        {
                            OperatorID = 3668,
                            FirstName = "Hayle",
                            LastName = "Gill"
                        },
                        new
                        {
                            OperatorID = 3579,
                            FirstName = "Ivan",
                            LastName = "Cooper"
                        },
                        new
                        {
                            OperatorID = 3499,
                            FirstName = "James",
                            LastName = "Young"
                        },
                        new
                        {
                            OperatorID = 3083,
                            FirstName = "Jason",
                            LastName = "Dingman"
                        },
                        new
                        {
                            OperatorID = 3608,
                            FirstName = "Jason",
                            LastName = "Wood"
                        },
                        new
                        {
                            OperatorID = 2972,
                            FirstName = "Jeff",
                            LastName = "Morris"
                        },
                        new
                        {
                            OperatorID = 3661,
                            FirstName = "Jennifer",
                            LastName = "O'Connor"
                        },
                        new
                        {
                            OperatorID = 3635,
                            FirstName = "Jeremy",
                            LastName = "Crawford"
                        },
                        new
                        {
                            OperatorID = 3515,
                            FirstName = "Jesse",
                            LastName = "Knott"
                        },
                        new
                        {
                            OperatorID = 3616,
                            FirstName = "John",
                            LastName = "Karmazyn"
                        },
                        new
                        {
                            OperatorID = 2705,
                            FirstName = "John",
                            LastName = "Sedgwick"
                        },
                        new
                        {
                            OperatorID = 3602,
                            FirstName = "Joseph",
                            LastName = "Dawson"
                        },
                        new
                        {
                            OperatorID = 3469,
                            FirstName = "Joshua",
                            LastName = "Herron"
                        },
                        new
                        {
                            OperatorID = 3628,
                            FirstName = "Justin",
                            LastName = "Graham"
                        },
                        new
                        {
                            OperatorID = 3638,
                            FirstName = "Justin",
                            LastName = "Vandenberg"
                        },
                        new
                        {
                            OperatorID = 3650,
                            FirstName = "Karen",
                            LastName = "Wright"
                        },
                        new
                        {
                            OperatorID = 3414,
                            FirstName = "Keith",
                            LastName = "Tripp"
                        },
                        new
                        {
                            OperatorID = 3055,
                            FirstName = "Kenneth",
                            LastName = "Abbott"
                        },
                        new
                        {
                            OperatorID = 3586,
                            FirstName = "Kenneth",
                            LastName = "Jones"
                        },
                        new
                        {
                            OperatorID = 2941,
                            FirstName = "Kenny",
                            LastName = "Herron"
                        },
                        new
                        {
                            OperatorID = 3450,
                            FirstName = "Kevin",
                            LastName = "Cork"
                        },
                        new
                        {
                            OperatorID = 3166,
                            FirstName = "Korwyn",
                            LastName = "Jones"
                        },
                        new
                        {
                            OperatorID = 3132,
                            FirstName = "Kristine",
                            LastName = "Cunha"
                        },
                        new
                        {
                            OperatorID = 2981,
                            FirstName = "Kriston",
                            LastName = "Spagnolo"
                        },
                        new
                        {
                            OperatorID = 3420,
                            FirstName = "Lee",
                            LastName = "Linton"
                        },
                        new
                        {
                            OperatorID = 3575,
                            FirstName = "Leo",
                            LastName = "Caissie"
                        },
                        new
                        {
                            OperatorID = 3613,
                            FirstName = "Linda",
                            LastName = "Weatherup"
                        },
                        new
                        {
                            OperatorID = 3121,
                            FirstName = "Lisa",
                            LastName = "Gosselin"
                        },
                        new
                        {
                            OperatorID = 2899,
                            FirstName = "Lisa",
                            LastName = "Haley"
                        },
                        new
                        {
                            OperatorID = 3520,
                            FirstName = "Lloyd",
                            LastName = "Weedman"
                        },
                        new
                        {
                            OperatorID = 3673,
                            FirstName = "Lori",
                            LastName = "Robinson"
                        },
                        new
                        {
                            OperatorID = 3288,
                            FirstName = "Mark",
                            LastName = "Bucciarelli"
                        },
                        new
                        {
                            OperatorID = 3221,
                            FirstName = "Mark",
                            LastName = "Mcgaughey"
                        },
                        new
                        {
                            OperatorID = 3620,
                            FirstName = "Mathew",
                            LastName = "Richards"
                        },
                        new
                        {
                            OperatorID = 3518,
                            FirstName = "Matthew",
                            LastName = "Crumb"
                        },
                        new
                        {
                            OperatorID = 3568,
                            FirstName = "Michael",
                            LastName = "Purdy"
                        },
                        new
                        {
                            OperatorID = 3160,
                            FirstName = "Michael",
                            LastName = "Sevigny"
                        },
                        new
                        {
                            OperatorID = 2712,
                            FirstName = "Mike",
                            LastName = "Lamers"
                        },
                        new
                        {
                            OperatorID = 3351,
                            FirstName = "Mindy",
                            LastName = "Baechler"
                        },
                        new
                        {
                            OperatorID = 3621,
                            FirstName = "Mitchel",
                            LastName = "Foster"
                        },
                        new
                        {
                            OperatorID = 3651,
                            FirstName = "Nadine",
                            LastName = "Owen"
                        },
                        new
                        {
                            OperatorID = 3670,
                            FirstName = "Nathan",
                            LastName = "Dickinson"
                        },
                        new
                        {
                            OperatorID = 2265,
                            FirstName = "Paul",
                            LastName = "Lagrois"
                        },
                        new
                        {
                            OperatorID = 3135,
                            FirstName = "Paul",
                            LastName = "Moynes"
                        },
                        new
                        {
                            OperatorID = 2945,
                            FirstName = "Paul",
                            LastName = "Raycraft"
                        },
                        new
                        {
                            OperatorID = 3578,
                            FirstName = "Rachel",
                            LastName = "Bell"
                        },
                        new
                        {
                            OperatorID = 3011,
                            FirstName = "Randal",
                            LastName = "Conley"
                        },
                        new
                        {
                            OperatorID = 3014,
                            FirstName = "Randy",
                            LastName = "Anderson"
                        },
                        new
                        {
                            OperatorID = 3330,
                            FirstName = "Ray",
                            LastName = "Stanley"
                        },
                        new
                        {
                            OperatorID = 3481,
                            FirstName = "Richard",
                            LastName = "Cook"
                        },
                        new
                        {
                            OperatorID = 2855,
                            FirstName = "Richard",
                            LastName = "Toomey"
                        },
                        new
                        {
                            OperatorID = 2887,
                            FirstName = "RonVan",
                            LastName = "Dorp"
                        },
                        new
                        {
                            OperatorID = 3618,
                            FirstName = "Rosemary",
                            LastName = "Buttar"
                        },
                        new
                        {
                            OperatorID = 3569,
                            FirstName = "Russell",
                            LastName = "Simpson"
                        },
                        new
                        {
                            OperatorID = 3480,
                            FirstName = "Sally",
                            LastName = "Shearer"
                        },
                        new
                        {
                            OperatorID = 2929,
                            FirstName = "Sam",
                            LastName = "Botrie"
                        },
                        new
                        {
                            OperatorID = 3155,
                            FirstName = "Scott",
                            LastName = "Eldridge"
                        },
                        new
                        {
                            OperatorID = 3106,
                            FirstName = "Sean",
                            LastName = "Walford"
                        },
                        new
                        {
                            OperatorID = 3478,
                            FirstName = "Shannon",
                            LastName = "Ferguson"
                        },
                        new
                        {
                            OperatorID = 3109,
                            FirstName = "Shawn",
                            LastName = "Lane"
                        },
                        new
                        {
                            OperatorID = 3459,
                            FirstName = "Shawn",
                            LastName = "Roy"
                        },
                        new
                        {
                            OperatorID = 3639,
                            FirstName = "Shawn",
                            LastName = "Sidle"
                        },
                        new
                        {
                            OperatorID = 2850,
                            FirstName = "Shawn",
                            LastName = "Turland"
                        },
                        new
                        {
                            OperatorID = 3463,
                            FirstName = "Shelley",
                            LastName = "Elliott"
                        },
                        new
                        {
                            OperatorID = 3353,
                            FirstName = "Sherry",
                            LastName = "Downes"
                        },
                        new
                        {
                            OperatorID = 3482,
                            FirstName = "Stephanie",
                            LastName = "Huffman"
                        },
                        new
                        {
                            OperatorID = 3607,
                            FirstName = "Stephanie",
                            LastName = "Pratt"
                        },
                        new
                        {
                            OperatorID = 3416,
                            FirstName = "Stephen",
                            LastName = "Dawson"
                        },
                        new
                        {
                            OperatorID = 2828,
                            FirstName = "Stephen",
                            LastName = "Ferguson"
                        },
                        new
                        {
                            OperatorID = 3676,
                            FirstName = "Stephen",
                            LastName = "King"
                        },
                        new
                        {
                            OperatorID = 3064,
                            FirstName = "Steve",
                            LastName = "Weekes"
                        },
                        new
                        {
                            OperatorID = 2831,
                            FirstName = "Steven",
                            LastName = "Vandenberg"
                        },
                        new
                        {
                            OperatorID = 3326,
                            FirstName = "Tammy",
                            LastName = "Godfrey"
                        },
                        new
                        {
                            OperatorID = 3462,
                            FirstName = "Teresa",
                            LastName = "Richardson"
                        },
                        new
                        {
                            OperatorID = 3577,
                            FirstName = "Terry",
                            LastName = "Robins"
                        },
                        new
                        {
                            OperatorID = 3648,
                            FirstName = "Thomas",
                            LastName = "Coupland"
                        },
                        new
                        {
                            OperatorID = 3677,
                            FirstName = "Thomas",
                            LastName = "Hogg"
                        },
                        new
                        {
                            OperatorID = 3007,
                            FirstName = "Tom",
                            LastName = "Dillabough"
                        },
                        new
                        {
                            OperatorID = 3556,
                            FirstName = "Travis",
                            LastName = "Bailey"
                        },
                        new
                        {
                            OperatorID = 3610,
                            FirstName = "Tyler",
                            LastName = "Davey"
                        },
                        new
                        {
                            OperatorID = 3601,
                            FirstName = "Tyler",
                            LastName = "Harnden"
                        },
                        new
                        {
                            OperatorID = 3497,
                            FirstName = "Warren",
                            LastName = "Dickinson"
                        },
                        new
                        {
                            OperatorID = 3678,
                            FirstName = "William",
                            LastName = "Ball"
                        },
                        new
                        {
                            OperatorID = 3039,
                            FirstName = "William",
                            LastName = "Eccleston"
                        },
                        new
                        {
                            OperatorID = 3615,
                            FirstName = "Zachary",
                            LastName = "Pandoff"
                        });
                });

            modelBuilder.Entity("LabourReporting.Models.OperatorWorkstation", b =>
                {
                    b.Property<int>("OperatorID");

                    b.Property<int>("WorkStationId");

                    b.HasKey("OperatorID", "WorkStationId");

                    b.HasIndex("WorkStationId");

                    b.ToTable("OperatorWorkstations");

                    b.HasData(
                        new
                        {
                            OperatorID = 3494,
                            WorkStationId = 2503
                        },
                        new
                        {
                            OperatorID = 3494,
                            WorkStationId = 133
                        },
                        new
                        {
                            OperatorID = 2873,
                            WorkStationId = 1110
                        },
                        new
                        {
                            OperatorID = 3460,
                            WorkStationId = 3701
                        },
                        new
                        {
                            OperatorID = 3679,
                            WorkStationId = 3101
                        },
                        new
                        {
                            OperatorID = 3449,
                            WorkStationId = 1180
                        },
                        new
                        {
                            OperatorID = 3510,
                            WorkStationId = 4701
                        },
                        new
                        {
                            OperatorID = 3485,
                            WorkStationId = 2403
                        },
                        new
                        {
                            OperatorID = 3417,
                            WorkStationId = 1110
                        },
                        new
                        {
                            OperatorID = 3058,
                            WorkStationId = 2703
                        },
                        new
                        {
                            OperatorID = 2834,
                            WorkStationId = 163
                        },
                        new
                        {
                            OperatorID = 2834,
                            WorkStationId = 162
                        },
                        new
                        {
                            OperatorID = 3049,
                            WorkStationId = 2701
                        },
                        new
                        {
                            OperatorID = 2745,
                            WorkStationId = 1801
                        },
                        new
                        {
                            OperatorID = 3604,
                            WorkStationId = 3701
                        },
                        new
                        {
                            OperatorID = 3654,
                            WorkStationId = 3102
                        },
                        new
                        {
                            OperatorID = 3154,
                            WorkStationId = 2101
                        },
                        new
                        {
                            OperatorID = 3183,
                            WorkStationId = 1100
                        },
                        new
                        {
                            OperatorID = 3559,
                            WorkStationId = 1801
                        },
                        new
                        {
                            OperatorID = 3672,
                            WorkStationId = 2503
                        },
                        new
                        {
                            OperatorID = 3672,
                            WorkStationId = 133
                        },
                        new
                        {
                            OperatorID = 3571,
                            WorkStationId = 3301
                        },
                        new
                        {
                            OperatorID = 3571,
                            WorkStationId = 3302
                        },
                        new
                        {
                            OperatorID = 3572,
                            WorkStationId = 3101
                        },
                        new
                        {
                            OperatorID = 3053,
                            WorkStationId = 2802
                        },
                        new
                        {
                            OperatorID = 3496,
                            WorkStationId = 4101
                        },
                        new
                        {
                            OperatorID = 3495,
                            WorkStationId = 4501
                        },
                        new
                        {
                            OperatorID = 3495,
                            WorkStationId = 4502
                        },
                        new
                        {
                            OperatorID = 3626,
                            WorkStationId = 77
                        },
                        new
                        {
                            OperatorID = 3626,
                            WorkStationId = 78
                        },
                        new
                        {
                            OperatorID = 2700,
                            WorkStationId = 1100
                        },
                        new
                        {
                            OperatorID = 3428,
                            WorkStationId = 4801
                        },
                        new
                        {
                            OperatorID = 3543,
                            WorkStationId = 3702
                        },
                        new
                        {
                            OperatorID = 3119,
                            WorkStationId = 2703
                        },
                        new
                        {
                            OperatorID = 3605,
                            WorkStationId = 3301
                        },
                        new
                        {
                            OperatorID = 3605,
                            WorkStationId = 3302
                        },
                        new
                        {
                            OperatorID = 3611,
                            WorkStationId = 4501
                        },
                        new
                        {
                            OperatorID = 3611,
                            WorkStationId = 4502
                        },
                        new
                        {
                            OperatorID = 3655,
                            WorkStationId = 2701
                        },
                        new
                        {
                            OperatorID = 3503,
                            WorkStationId = 4401
                        },
                        new
                        {
                            OperatorID = 3542,
                            WorkStationId = 2102
                        },
                        new
                        {
                            OperatorID = 2849,
                            WorkStationId = 3401
                        },
                        new
                        {
                            OperatorID = 2980,
                            WorkStationId = 2901
                        },
                        new
                        {
                            OperatorID = 3091,
                            WorkStationId = 3501
                        },
                        new
                        {
                            OperatorID = 3171,
                            WorkStationId = 2901
                        },
                        new
                        {
                            OperatorID = 3013,
                            WorkStationId = 3701
                        },
                        new
                        {
                            OperatorID = 3175,
                            WorkStationId = 3301
                        },
                        new
                        {
                            OperatorID = 3175,
                            WorkStationId = 3302
                        },
                        new
                        {
                            OperatorID = 2914,
                            WorkStationId = 1180
                        },
                        new
                        {
                            OperatorID = 3343,
                            WorkStationId = 2802
                        },
                        new
                        {
                            OperatorID = 3687,
                            WorkStationId = 4702
                        },
                        new
                        {
                            OperatorID = 3059,
                            WorkStationId = 2102
                        },
                        new
                        {
                            OperatorID = 3108,
                            WorkStationId = 1180
                        },
                        new
                        {
                            OperatorID = 3649,
                            WorkStationId = 2403
                        },
                        new
                        {
                            OperatorID = 3065,
                            WorkStationId = 1100
                        },
                        new
                        {
                            OperatorID = 3291,
                            WorkStationId = 3101
                        },
                        new
                        {
                            OperatorID = 3161,
                            WorkStationId = 2101
                        },
                        new
                        {
                            OperatorID = 3617,
                            WorkStationId = 2301
                        },
                        new
                        {
                            OperatorID = 3617,
                            WorkStationId = 2302
                        },
                        new
                        {
                            OperatorID = 2593,
                            WorkStationId = 2403
                        },
                        new
                        {
                            OperatorID = 3120,
                            WorkStationId = 3702
                        },
                        new
                        {
                            OperatorID = 3522,
                            WorkStationId = 4702
                        },
                        new
                        {
                            OperatorID = 2982,
                            WorkStationId = 3801
                        },
                        new
                        {
                            OperatorID = 2756,
                            WorkStationId = 3401
                        },
                        new
                        {
                            OperatorID = 3668,
                            WorkStationId = 2401
                        },
                        new
                        {
                            OperatorID = 3579,
                            WorkStationId = 4701
                        },
                        new
                        {
                            OperatorID = 3499,
                            WorkStationId = 1801
                        },
                        new
                        {
                            OperatorID = 3083,
                            WorkStationId = 162
                        },
                        new
                        {
                            OperatorID = 3083,
                            WorkStationId = 163
                        },
                        new
                        {
                            OperatorID = 3608,
                            WorkStationId = 2401
                        },
                        new
                        {
                            OperatorID = 2972,
                            WorkStationId = 3501
                        },
                        new
                        {
                            OperatorID = 3661,
                            WorkStationId = 3901
                        },
                        new
                        {
                            OperatorID = 3635,
                            WorkStationId = 3401
                        },
                        new
                        {
                            OperatorID = 3515,
                            WorkStationId = 3801
                        },
                        new
                        {
                            OperatorID = 3616,
                            WorkStationId = 3401
                        },
                        new
                        {
                            OperatorID = 2705,
                            WorkStationId = 2901
                        },
                        new
                        {
                            OperatorID = 3602,
                            WorkStationId = 4702
                        },
                        new
                        {
                            OperatorID = 3469,
                            WorkStationId = 3401
                        },
                        new
                        {
                            OperatorID = 3628,
                            WorkStationId = 3801
                        },
                        new
                        {
                            OperatorID = 3638,
                            WorkStationId = 2101
                        },
                        new
                        {
                            OperatorID = 3650,
                            WorkStationId = 3901
                        },
                        new
                        {
                            OperatorID = 3414,
                            WorkStationId = 77
                        },
                        new
                        {
                            OperatorID = 3414,
                            WorkStationId = 78
                        },
                        new
                        {
                            OperatorID = 3055,
                            WorkStationId = 3401
                        },
                        new
                        {
                            OperatorID = 3586,
                            WorkStationId = 2101
                        },
                        new
                        {
                            OperatorID = 2941,
                            WorkStationId = 2702
                        },
                        new
                        {
                            OperatorID = 3450,
                            WorkStationId = 4702
                        },
                        new
                        {
                            OperatorID = 3166,
                            WorkStationId = 1100
                        },
                        new
                        {
                            OperatorID = 3132,
                            WorkStationId = 3901
                        },
                        new
                        {
                            OperatorID = 2981,
                            WorkStationId = 4901
                        },
                        new
                        {
                            OperatorID = 3420,
                            WorkStationId = 1110
                        },
                        new
                        {
                            OperatorID = 3575,
                            WorkStationId = 4702
                        },
                        new
                        {
                            OperatorID = 3613,
                            WorkStationId = 3101
                        },
                        new
                        {
                            OperatorID = 3121,
                            WorkStationId = 2802
                        },
                        new
                        {
                            OperatorID = 2899,
                            WorkStationId = 3801
                        },
                        new
                        {
                            OperatorID = 3520,
                            WorkStationId = 3701
                        },
                        new
                        {
                            OperatorID = 3673,
                            WorkStationId = 3101
                        },
                        new
                        {
                            OperatorID = 3288,
                            WorkStationId = 2102
                        },
                        new
                        {
                            OperatorID = 3221,
                            WorkStationId = 2702
                        },
                        new
                        {
                            OperatorID = 3620,
                            WorkStationId = 3102
                        },
                        new
                        {
                            OperatorID = 3518,
                            WorkStationId = 2703
                        },
                        new
                        {
                            OperatorID = 3568,
                            WorkStationId = 3501
                        },
                        new
                        {
                            OperatorID = 3160,
                            WorkStationId = 4801
                        },
                        new
                        {
                            OperatorID = 2712,
                            WorkStationId = 2801
                        },
                        new
                        {
                            OperatorID = 3351,
                            WorkStationId = 2301
                        },
                        new
                        {
                            OperatorID = 3351,
                            WorkStationId = 2302
                        },
                        new
                        {
                            OperatorID = 3621,
                            WorkStationId = 3701
                        },
                        new
                        {
                            OperatorID = 3651,
                            WorkStationId = 2901
                        },
                        new
                        {
                            OperatorID = 3670,
                            WorkStationId = 3801
                        },
                        new
                        {
                            OperatorID = 2265,
                            WorkStationId = 2702
                        },
                        new
                        {
                            OperatorID = 3135,
                            WorkStationId = 4901
                        },
                        new
                        {
                            OperatorID = 2945,
                            WorkStationId = 2702
                        },
                        new
                        {
                            OperatorID = 3578,
                            WorkStationId = 2301
                        },
                        new
                        {
                            OperatorID = 3578,
                            WorkStationId = 2302
                        },
                        new
                        {
                            OperatorID = 3011,
                            WorkStationId = 4401
                        },
                        new
                        {
                            OperatorID = 3014,
                            WorkStationId = 1180
                        },
                        new
                        {
                            OperatorID = 3330,
                            WorkStationId = 2703
                        },
                        new
                        {
                            OperatorID = 3481,
                            WorkStationId = 77
                        },
                        new
                        {
                            OperatorID = 3481,
                            WorkStationId = 78
                        },
                        new
                        {
                            OperatorID = 2855,
                            WorkStationId = 162
                        },
                        new
                        {
                            OperatorID = 2855,
                            WorkStationId = 163
                        },
                        new
                        {
                            OperatorID = 2887,
                            WorkStationId = 2701
                        },
                        new
                        {
                            OperatorID = 3618,
                            WorkStationId = 2802
                        },
                        new
                        {
                            OperatorID = 3569,
                            WorkStationId = 2503
                        },
                        new
                        {
                            OperatorID = 3569,
                            WorkStationId = 133
                        },
                        new
                        {
                            OperatorID = 3480,
                            WorkStationId = 2901
                        },
                        new
                        {
                            OperatorID = 2929,
                            WorkStationId = 4701
                        },
                        new
                        {
                            OperatorID = 3155,
                            WorkStationId = 3702
                        },
                        new
                        {
                            OperatorID = 3106,
                            WorkStationId = 4101
                        },
                        new
                        {
                            OperatorID = 3478,
                            WorkStationId = 3301
                        },
                        new
                        {
                            OperatorID = 3478,
                            WorkStationId = 3302
                        },
                        new
                        {
                            OperatorID = 3109,
                            WorkStationId = 4701
                        },
                        new
                        {
                            OperatorID = 3459,
                            WorkStationId = 3701
                        },
                        new
                        {
                            OperatorID = 3639,
                            WorkStationId = 4401
                        },
                        new
                        {
                            OperatorID = 2850,
                            WorkStationId = 2801
                        },
                        new
                        {
                            OperatorID = 3463,
                            WorkStationId = 3401
                        },
                        new
                        {
                            OperatorID = 3353,
                            WorkStationId = 3401
                        },
                        new
                        {
                            OperatorID = 3482,
                            WorkStationId = 77
                        },
                        new
                        {
                            OperatorID = 3482,
                            WorkStationId = 78
                        },
                        new
                        {
                            OperatorID = 3607,
                            WorkStationId = 2403
                        },
                        new
                        {
                            OperatorID = 3416,
                            WorkStationId = 4101
                        },
                        new
                        {
                            OperatorID = 2828,
                            WorkStationId = 2503
                        },
                        new
                        {
                            OperatorID = 2828,
                            WorkStationId = 133
                        },
                        new
                        {
                            OperatorID = 3676,
                            WorkStationId = 3702
                        },
                        new
                        {
                            OperatorID = 3064,
                            WorkStationId = 2701
                        },
                        new
                        {
                            OperatorID = 2831,
                            WorkStationId = 77
                        },
                        new
                        {
                            OperatorID = 2831,
                            WorkStationId = 78
                        },
                        new
                        {
                            OperatorID = 3326,
                            WorkStationId = 2901
                        },
                        new
                        {
                            OperatorID = 3462,
                            WorkStationId = 2401
                        },
                        new
                        {
                            OperatorID = 3577,
                            WorkStationId = 3801
                        },
                        new
                        {
                            OperatorID = 3648,
                            WorkStationId = 4401
                        },
                        new
                        {
                            OperatorID = 3677,
                            WorkStationId = 1110
                        },
                        new
                        {
                            OperatorID = 3007,
                            WorkStationId = 162
                        },
                        new
                        {
                            OperatorID = 3007,
                            WorkStationId = 163
                        },
                        new
                        {
                            OperatorID = 3556,
                            WorkStationId = 1110
                        },
                        new
                        {
                            OperatorID = 3610,
                            WorkStationId = 3102
                        },
                        new
                        {
                            OperatorID = 3601,
                            WorkStationId = 4501
                        },
                        new
                        {
                            OperatorID = 3601,
                            WorkStationId = 4502
                        },
                        new
                        {
                            OperatorID = 3497,
                            WorkStationId = 4501
                        },
                        new
                        {
                            OperatorID = 3497,
                            WorkStationId = 4502
                        },
                        new
                        {
                            OperatorID = 3678,
                            WorkStationId = 3102
                        },
                        new
                        {
                            OperatorID = 3039,
                            WorkStationId = 4101
                        },
                        new
                        {
                            OperatorID = 3615,
                            WorkStationId = 2101
                        });
                });

            modelBuilder.Entity("LabourReporting.Models.WorkStation", b =>
                {
                    b.Property<int>("WorkStationId");

                    b.Property<int>("Department");

                    b.Property<string>("WorkStationName")
                        .IsRequired();

                    b.HasKey("WorkStationId");

                    b.ToTable("WorkStations");

                    b.HasData(
                        new
                        {
                            WorkStationId = 1801,
                            Department = 1,
                            WorkStationName = "1801 Buncher"
                        },
                        new
                        {
                            WorkStationId = 1100,
                            Department = 1,
                            WorkStationName = "1100 Breakdown"
                        },
                        new
                        {
                            WorkStationId = 1180,
                            Department = 1,
                            WorkStationName = "1180 Planetary"
                        },
                        new
                        {
                            WorkStationId = 1110,
                            Department = 1,
                            WorkStationName = "1110 Intermediate"
                        },
                        new
                        {
                            WorkStationId = 2101,
                            Department = 2,
                            WorkStationName = "2101 Extruder"
                        },
                        new
                        {
                            WorkStationId = 2102,
                            Department = 2,
                            WorkStationName = "2102 Extruder"
                        },
                        new
                        {
                            WorkStationId = 2301,
                            Department = 2,
                            WorkStationName = "2301 Twinner"
                        },
                        new
                        {
                            WorkStationId = 2302,
                            Department = 2,
                            WorkStationName = "2302 Twinner"
                        },
                        new
                        {
                            WorkStationId = 2401,
                            Department = 2,
                            WorkStationName = "2401 Cabler"
                        },
                        new
                        {
                            WorkStationId = 2402,
                            Department = 2,
                            WorkStationName = "2402 Cabler"
                        },
                        new
                        {
                            WorkStationId = 2403,
                            Department = 2,
                            WorkStationName = "2403 Cabler"
                        },
                        new
                        {
                            WorkStationId = 2404,
                            Department = 2,
                            WorkStationName = "2404 Cabler"
                        },
                        new
                        {
                            WorkStationId = 2405,
                            Department = 2,
                            WorkStationName = "2405 Cabler"
                        },
                        new
                        {
                            WorkStationId = 2701,
                            Department = 2,
                            WorkStationName = "2701 Jacket"
                        },
                        new
                        {
                            WorkStationId = 2702,
                            Department = 2,
                            WorkStationName = "2702 Jacket"
                        },
                        new
                        {
                            WorkStationId = 2703,
                            Department = 2,
                            WorkStationName = "2703 Jacket"
                        },
                        new
                        {
                            WorkStationId = 163,
                            Department = 2,
                            WorkStationName = "163 Armour"
                        },
                        new
                        {
                            WorkStationId = 162,
                            Department = 2,
                            WorkStationName = "162 Armour"
                        },
                        new
                        {
                            WorkStationId = 77,
                            Department = 2,
                            WorkStationName = "77 Armour"
                        },
                        new
                        {
                            WorkStationId = 78,
                            Department = 2,
                            WorkStationName = "78 Armour"
                        },
                        new
                        {
                            WorkStationId = 133,
                            Department = 2,
                            WorkStationName = "133 Armour"
                        },
                        new
                        {
                            WorkStationId = 2503,
                            Department = 2,
                            WorkStationName = "Myrtle"
                        },
                        new
                        {
                            WorkStationId = 2901,
                            Department = 2,
                            WorkStationName = "Tester"
                        },
                        new
                        {
                            WorkStationId = 2801,
                            Department = 2,
                            WorkStationName = "2801 Rewinder"
                        },
                        new
                        {
                            WorkStationId = 2802,
                            Department = 2,
                            WorkStationName = "2802 Rewinder"
                        },
                        new
                        {
                            WorkStationId = 3101,
                            Department = 3,
                            WorkStationName = "3101 Extruder"
                        },
                        new
                        {
                            WorkStationId = 3102,
                            Department = 3,
                            WorkStationName = "3102 Extruder"
                        },
                        new
                        {
                            WorkStationId = 3301,
                            Department = 3,
                            WorkStationName = "3301 Twinner"
                        },
                        new
                        {
                            WorkStationId = 3302,
                            Department = 3,
                            WorkStationName = "3302 Twinner"
                        },
                        new
                        {
                            WorkStationId = 3401,
                            Department = 3,
                            WorkStationName = "3401 cabler"
                        },
                        new
                        {
                            WorkStationId = 3501,
                            Department = 3,
                            WorkStationName = "3501 Armour"
                        },
                        new
                        {
                            WorkStationId = 3502,
                            Department = 3,
                            WorkStationName = "3502 Armour"
                        },
                        new
                        {
                            WorkStationId = 3701,
                            Department = 3,
                            WorkStationName = "3701 Jacket"
                        },
                        new
                        {
                            WorkStationId = 3702,
                            Department = 3,
                            WorkStationName = "3702 Jacket"
                        },
                        new
                        {
                            WorkStationId = 3801,
                            Department = 3,
                            WorkStationName = "3801 Rewinder"
                        },
                        new
                        {
                            WorkStationId = 3901,
                            Department = 3,
                            WorkStationName = "3901 Tester"
                        },
                        new
                        {
                            WorkStationId = 4101,
                            Department = 4,
                            WorkStationName = "4101 Extruder"
                        },
                        new
                        {
                            WorkStationId = 4401,
                            Department = 4,
                            WorkStationName = "4401 Cabler"
                        },
                        new
                        {
                            WorkStationId = 4701,
                            Department = 4,
                            WorkStationName = "4701 Jacket"
                        },
                        new
                        {
                            WorkStationId = 4702,
                            Department = 4,
                            WorkStationName = "4702 Jacket"
                        },
                        new
                        {
                            WorkStationId = 4501,
                            Department = 4,
                            WorkStationName = "4501 Armour"
                        },
                        new
                        {
                            WorkStationId = 4502,
                            Department = 4,
                            WorkStationName = "4502 Armour"
                        },
                        new
                        {
                            WorkStationId = 4801,
                            Department = 4,
                            WorkStationName = "4801 Rewinder"
                        },
                        new
                        {
                            WorkStationId = 4901,
                            Department = 4,
                            WorkStationName = "4901 Tester"
                        },
                        new
                        {
                            WorkStationId = 5501,
                            Department = 2,
                            WorkStationName = "5501 Armour"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("LabourReporting.Models.LabourReport", b =>
                {
                    b.HasOne("LabourReporting.Models.Operator", "Operators")
                        .WithMany("LabourReports")
                        .HasForeignKey("OperatorID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LabourReporting.Models.NcrTag", b =>
                {
                    b.HasOne("LabourReporting.Models.Operator", "Operator")
                        .WithMany("NcrTags")
                        .HasForeignKey("OperatorId");

                    b.HasOne("LabourReporting.Models.WorkStation", "WorkStation")
                        .WithMany("NcrTags")
                        .HasForeignKey("WorkStationId");
                });

            modelBuilder.Entity("LabourReporting.Models.OperatorWorkstation", b =>
                {
                    b.HasOne("LabourReporting.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LabourReporting.Models.WorkStation", "WorkStation")
                        .WithMany()
                        .HasForeignKey("WorkStationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
